local S = minetest.get_translator("kilns")

crafting.register_recipe(
	{
		output = "kiln",
		type = "inv",
		items = {"cobble 4"},
		always_known = true,
	})



--node registration
------------------------------------------------------------------------
local on_timer, on_punch, on_rightclick, on_construct =
	dofile(minetest.get_modpath("kilns") .. "/kiln_node_callbacks.lua")

minetest.register_node("kilns:kiln_off",
	{
		description = S("Kiln"),
		paramtype2 = "facedir",
		is_ground_content = false,
		drawtype = "mesh",
		mesh = "kilns_kiln.obj",
		tiles = {"kilns_kiln_off.png"},
		groups = {cracky = 2,},
		sounds = generic_media.node_sound_stone_defaults(),
		sunlight_propagates = true,

		collision_box =
		{
			type = "fixed",
			fixed = {
				{-0.5, -0.5, -0.5, 0.5, 0, 0.5},
			},
		},
		on_rightclick = on_rightclick,
		on_punch = on_punch,
		on_construct = on_construct,
		on_timer = on_timer,
		stack_max = 2,
	})
minetest.register_node("kilns:kiln_on",
	{
		description = S("Kiln"),
		paramtype2 = "facedir",
		is_ground_content = false,
		drawtype = "mesh",
		mesh = "kilns_kiln.obj",
		tiles = {"kilns_kiln_on.png"},
		groups = {cracky = 2, not_in_creative_inventory = 1,},
		sounds = generic_media.node_sound_stone_defaults(),
		sunlight_propagates = true,
		light_source = 14,
		collision_box = {
			type = "fixed",
			fixed = {
				{-0.5, -0.5, -0.5, 0.5, 0, 0.5},
				{-0.25, 0, -0.25, 0.25, 0.5, 0.25},
			},
		},
		drop = "kiln",
		on_rightclick = on_rightclick,
		on_punch = on_punch,
		on_construct = on_construct,
		on_timer = on_timer,
	})
minetest.register_alias("kiln", "kilns:kiln_off")
